disabled_rules: # rule identifiers to exclude from running
  - line_length
  - identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

function_body_length:
    warning: 50
    error: 100

opt_in_rules:
- closure_spacing
- contains_over_first_not_nil
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- first_where
- joined_default_parameter
- modifier_order
- multiline_arguments
- multiline_parameters
- operator_usage_whitespace
- overridden_super_call
- pattern_matching_keywords
- prohibited_super_call
- redundant_nil_coalescing
- sorted_first_last
- sorted_imports
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- yoda_condition

